# Form implementation generated from reading ui file 'QtApplication.ui'
#
# Created by: PyQt6 UI code generator 6.1.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(519, 509)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 361, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.HorizontalInput_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.HorizontalInput_Layout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalInput_Layout.setObjectName("HorizontalInput_Layout")
        self.ReadingDir_Label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.ReadingDir_Label.setFont(font)
        self.ReadingDir_Label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.ReadingDir_Label.setObjectName("ReadingDir_Label")
        self.HorizontalInput_Layout.addWidget(self.ReadingDir_Label)
        self.InputButtonContainer_Frame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.InputButtonContainer_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.InputButtonContainer_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.InputButtonContainer_Frame.setObjectName("InputButtonContainer_Frame")
        self.Input_Button = QtWidgets.QPushButton(self.InputButtonContainer_Frame)
        self.Input_Button.setGeometry(QtCore.QRect(25, 5, 93, 28))
        self.Input_Button.setObjectName("Input_Button")
        self.HorizontalInput_Layout.addWidget(self.InputButtonContainer_Frame)
        self.InputText_Field = QtWidgets.QTextBrowser(self.centralwidget)
        self.InputText_Field.setEnabled(False)
        self.InputText_Field.setGeometry(QtCore.QRect(20, 60, 351, 31))
        self.InputText_Field.setObjectName("InputText_Field")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 361, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.HorizontalOutput_Layout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.HorizontalOutput_Layout.setContentsMargins(0, 0, 0, 0)
        self.HorizontalOutput_Layout.setObjectName("HorizontalOutput_Layout")
        self.WritingDir_Label = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.WritingDir_Label.setFont(font)
        self.WritingDir_Label.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.WritingDir_Label.setObjectName("WritingDir_Label")
        self.HorizontalOutput_Layout.addWidget(self.WritingDir_Label)
        self.OutputButtonContainer_Frame = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.OutputButtonContainer_Frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.OutputButtonContainer_Frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.OutputButtonContainer_Frame.setObjectName("OutputButtonContainer_Frame")
        self.Output_Button = QtWidgets.QPushButton(self.OutputButtonContainer_Frame)
        self.Output_Button.setGeometry(QtCore.QRect(25, 5, 93, 28))
        self.Output_Button.setObjectName("Output_Button")
        self.HorizontalOutput_Layout.addWidget(self.OutputButtonContainer_Frame)
        self.OutputText_Field = QtWidgets.QTextBrowser(self.centralwidget)
        self.OutputText_Field.setEnabled(False)
        self.OutputText_Field.setGeometry(QtCore.QRect(20, 160, 351, 31))
        self.OutputText_Field.setObjectName("OutputText_Field")
        self.Process_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Process_Button.setEnabled(False)
        self.Process_Button.setGeometry(QtCore.QRect(400, 25, 93, 28))
        self.Process_Button.setObjectName("Process_Button")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(385, 20, 16, 171))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.Close_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Close_Button.setGeometry(QtCore.QRect(400, 60, 93, 28))
        self.Close_Button.setObjectName("Close_Button")
        self.Registers_Checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.Registers_Checkbox.setEnabled(True)
        self.Registers_Checkbox.setGeometry(QtCore.QRect(20, 220, 141, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Registers_Checkbox.setFont(font)
        self.Registers_Checkbox.setObjectName("Registers_Checkbox")
        self.Registers_Field = QtWidgets.QTextEdit(self.centralwidget)
        self.Registers_Field.setEnabled(False)
        self.Registers_Field.setGeometry(QtCore.QRect(20, 250, 471, 31))
        self.Registers_Field.setObjectName("Registers_Field")
        self.LogOutput_Field = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.LogOutput_Field.setGeometry(QtCore.QRect(20, 320, 471, 131))
        self.LogOutput_Field.setObjectName("LogOutput_Field")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(70, 295, 421, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 295, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label.setFont(font)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 519, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.ReadingDir_Label.setText(_translate("MainWindow", "Selecionar Diretorio de Leitura"))
        self.Input_Button.setText(_translate("MainWindow", "Selecionar"))
        self.WritingDir_Label.setText(_translate("MainWindow", "Selecionar Diretorio de Leitura"))
        self.Output_Button.setText(_translate("MainWindow", "Selecionar"))
        self.Process_Button.setText(_translate("MainWindow", "Process"))
        self.Close_Button.setText(_translate("MainWindow", "Fechar"))
        self.Registers_Checkbox.setText(_translate("MainWindow", "Selecionar Registros"))
        self.label.setText(_translate("MainWindow", "Logger"))

    def click_selecionar_input(self):
        """
        This function will open up a window to select the directory
        :return: Directory Name
        :rtype: str
        """
        #dir_ = QtGui

    def click_selecionar_output(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
