# -*- mode: python ; coding: utf-8 -*-
import sys
sys.setrecursionlimit(sys.getrecursionlimit()*7)
print("Recursion limit:", sys.getrecursionlimit())

block_cipher = None


a = Analysis(['main.py'],
             pathex=['C:\\MyDevProjects\\Extrator SPED Fiscal'],
             binaries=[],
             datas=[],
             hiddenimports=['Core.Block_0', 'Core.Block_1', 'Core.Block_9',
                            'Core.Block_B', 'Core.Block_C', 'Core.Block_D',
                            'Core.Block_E', 'Core.Block_G', 'Core.Block_H',
                            'Core.Block_K', 'Core.Null_Factory',
                            'Core.Block_0.R0000_Factory', 'Core.Block_0.R0001_Factory', 'Core.Block_0.R0002_Factory',
                            'Core.Block_0.R0005_Factory', 'Core.Block_0.R0015_Factory', 'Core.Block_0.R0100_Factory',
                            'Core.Block_0.R0150_Factory', 'Core.Block_0.R0175_Factory', 'Core.Block_0.R0190_Factory',
                            'Core.Block_0.R0200_Factory', 'Core.Block_0.R0205_Factory', 'Core.Block_0.R0206_Factory',
                            'Core.Block_0.R0210_Factory', 'Core.Block_0.R0220_Factory', 'Core.Block_0.R0300_Factory',
                            'Core.Block_0.R0305_Factory', 'Core.Block_0.R0400_Factory', 'Core.Block_0.R0450_Factory',
                            'Core.Block_0.R0460_Factory', 'Core.Block_0.R0500_Factory', 'Core.Block_0.R0600_Factory',
                            'Core.Block_0.R0990_Factory', 'Core.Block_1.R1001_Factory', 'Core.Block_1.R1010_Factory',
                            'Core.Block_1.R1100_Factory', 'Core.Block_1.R1105_Factory', 'Core.Block_1.R1110_Factory',
                            'Core.Block_1.R1200_Factory', 'Core.Block_1.R1210_Factory', 'Core.Block_1.R1250_Factory',
                            'Core.Block_1.R1255_Factory', 'Core.Block_1.R1300_Factory', 'Core.Block_1.R1310_Factory',
                            'Core.Block_1.R1320_Factory', 'Core.Block_1.R1350_Factory', 'Core.Block_1.R1360_Factory',
                            'Core.Block_1.R1370_Factory', 'Core.Block_1.R1390_Factory', 'Core.Block_1.R1391_Factory',
                            'Core.Block_1.R1400_Factory', 'Core.Block_1.R1500_Factory', 'Core.Block_1.R1510_Factory',
                            'Core.Block_1.R1600_Factory', 'Core.Block_1.R1700_Factory', 'Core.Block_1.R1710_Factory',
                            'Core.Block_1.R1800_Factory', 'Core.Block_1.R1900_Factory', 'Core.Block_1.R1910_Factory',
                            'Core.Block_1.R1920_Factory', 'Core.Block_1.R1921_Factory', 'Core.Block_1.R1922_Factory',
                            'Core.Block_1.R1923_Factory', 'Core.Block_1.R1925_Factory', 'Core.Block_1.R1926_Factory',
                            'Core.Block_1.R1960_Factory', 'Core.Block_1.R1970_Factory', 'Core.Block_1.R1975_Factory',
                            'Core.Block_1.R1980_Factory', 'Core.Block_1.R1990_Factory', 'Core.Block_9.R9001_Factory',
                            'Core.Block_9.R9900_Factory', 'Core.Block_9.R9990_Factory', 'Core.Block_9.R9999_Factory',
                            'Core.Block_B.RB001_Factory', 'Core.Block_B.RB020_Factory', 'Core.Block_B.RB025_Factory',
                            'Core.Block_B.RB030_Factory', 'Core.Block_B.RB035_Factory', 'Core.Block_B.RB350_Factory',
                            'Core.Block_B.RB420_Factory', 'Core.Block_B.RB440_Factory', 'Core.Block_B.RB460_Factory',
                            'Core.Block_B.RB470_Factory', 'Core.Block_B.RB500_Factory', 'Core.Block_B.RB510_Factory',
                            'Core.Block_B.RB990_Factory', 'Core.Block_C.RC001_Factory', 'Core.Block_C.RC100_Factory',
                            'Core.Block_C.RC101_Factory', 'Core.Block_C.RC105_Factory', 'Core.Block_C.RC110_Factory',
                            'Core.Block_C.RC111_Factory', 'Core.Block_C.RC112_Factory', 'Core.Block_C.RC113_Factory',
                            'Core.Block_C.RC114_Factory', 'Core.Block_C.RC115_Factory', 'Core.Block_C.RC116_Factory',
                            'Core.Block_C.RC120_Factory', 'Core.Block_C.RC130_Factory', 'Core.Block_C.RC140_Factory',
                            'Core.Block_C.RC141_Factory', 'Core.Block_C.RC160_Factory', 'Core.Block_C.RC165_Factory',
                            'Core.Block_C.RC170_Factory', 'Core.Block_C.RC171_Factory', 'Core.Block_C.RC172_Factory',
                            'Core.Block_C.RC173_Factory', 'Core.Block_C.RC174_Factory', 'Core.Block_C.RC175_Factory',
                            'Core.Block_C.RC176_Factory', 'Core.Block_C.RC177_Factory', 'Core.Block_C.RC178_Factory',
                            'Core.Block_C.RC179_Factory', 'Core.Block_C.RC180_Factory', 'Core.Block_C.RC181_Factory',
                            'Core.Block_C.RC185_Factory', 'Core.Block_C.RC186_Factory', 'Core.Block_C.RC190_Factory',
                            'Core.Block_C.RC191_Factory', 'Core.Block_C.RC195_Factory', 'Core.Block_C.RC197_Factory',
                            'Core.Block_C.RC300_Factory', 'Core.Block_C.RC310_Factory', 'Core.Block_C.RC320_Factory',
                            'Core.Block_C.RC321_Factory', 'Core.Block_C.RC330_Factory', 'Core.Block_C.RC350_Factory',
                            'Core.Block_C.RC370_Factory', 'Core.Block_C.RC380_Factory', 'Core.Block_C.RC390_Factory',
                            'Core.Block_C.RC400_Factory', 'Core.Block_C.RC405_Factory', 'Core.Block_C.RC410_Factory',
                            'Core.Block_C.RC420_Factory', 'Core.Block_C.RC425_Factory', 'Core.Block_C.RC430_Factory',
                            'Core.Block_C.RC460_Factory', 'Core.Block_C.RC465_Factory', 'Core.Block_C.RC470_Factory',
                            'Core.Block_C.RC480_Factory', 'Core.Block_C.RC490_Factory', 'Core.Block_C.RC495_Factory',
                            'Core.Block_C.RC500_Factory', 'Core.Block_C.RC510_Factory', 'Core.Block_C.RC590_Factory',
                            'Core.Block_C.RC591_Factory', 'Core.Block_C.RC595_Factory', 'Core.Block_C.RC597_Factory',
                            'Core.Block_C.RC600_Factory', 'Core.Block_C.RC601_Factory', 'Core.Block_C.RC610_Factory',
                            'Core.Block_C.RC690_Factory', 'Core.Block_C.RC700_Factory', 'Core.Block_C.RC790_Factory',
                            'Core.Block_C.RC791_Factory', 'Core.Block_C.RC800_Factory', 'Core.Block_C.RC810_Factory',
                            'Core.Block_C.RC815_Factory', 'Core.Block_C.RC850_Factory', 'Core.Block_C.RC860_Factory',
                            'Core.Block_C.RC870_Factory', 'Core.Block_C.RC880_Factory', 'Core.Block_C.RC890_Factory',
                            'Core.Block_C.RC990_Factory', 'Core.Block_D.RD001_Factory', 'Core.Block_D.RD100_Factory',
                            'Core.Block_D.RD101_Factory', 'Core.Block_D.RD110_Factory', 'Core.Block_D.RD120_Factory',
                            'Core.Block_D.RD130_Factory', 'Core.Block_D.RD140_Factory', 'Core.Block_D.RD150_Factory',
                            'Core.Block_D.RD160_Factory', 'Core.Block_D.RD161_Factory', 'Core.Block_D.RD162_Factory',
                            'Core.Block_D.RD170_Factory', 'Core.Block_D.RD180_Factory', 'Core.Block_D.RD190_Factory',
                            'Core.Block_D.RD195_Factory', 'Core.Block_D.RD197_Factory', 'Core.Block_D.RD300_Factory',
                            'Core.Block_D.RD301_Factory', 'Core.Block_D.RD310_Factory', 'Core.Block_D.RD350_Factory',
                            'Core.Block_D.RD355_Factory', 'Core.Block_D.RD360_Factory', 'Core.Block_D.RD365_Factory',
                            'Core.Block_D.RD370_Factory', 'Core.Block_D.RD390_Factory', 'Core.Block_D.RD400_Factory',
                            'Core.Block_D.RD410_Factory', 'Core.Block_D.RD411_Factory', 'Core.Block_D.RD420_Factory',
                            'Core.Block_D.RD500_Factory', 'Core.Block_D.RD510_Factory', 'Core.Block_D.RD530_Factory',
                            'Core.Block_D.RD590_Factory', 'Core.Block_D.RD600_Factory', 'Core.Block_D.RD610_Factory',
                            'Core.Block_D.RD690_Factory', 'Core.Block_D.RD695_Factory', 'Core.Block_D.RD696_Factory',
                            'Core.Block_D.RD697_Factory', 'Core.Block_D.RD990_Factory', 'Core.Block_E.RE001_Factory',
                            'Core.Block_E.RE100_Factory', 'Core.Block_E.RE110_Factory', 'Core.Block_E.RE111_Factory',
                            'Core.Block_E.RE112_Factory', 'Core.Block_E.RE113_Factory', 'Core.Block_E.RE115_Factory',
                            'Core.Block_E.RE116_Factory', 'Core.Block_E.RE200_Factory', 'Core.Block_E.RE210_Factory',
                            'Core.Block_E.RE220_Factory', 'Core.Block_E.RE230_Factory', 'Core.Block_E.RE240_Factory',
                            'Core.Block_E.RE250_Factory', 'Core.Block_E.RE300_Factory', 'Core.Block_E.RE310_Factory',
                            'Core.Block_E.RE311_Factory', 'Core.Block_E.RE312_Factory', 'Core.Block_E.RE313_Factory',
                            'Core.Block_E.RE316_Factory', 'Core.Block_E.RE500_Factory', 'Core.Block_E.RE510_Factory',
                            'Core.Block_E.RE520_Factory', 'Core.Block_E.RE530_Factory', 'Core.Block_E.RE531_Factory',
                            'Core.Block_E.RE990_Factory', 'Core.Block_G.RG001_Factory', 'Core.Block_G.RG110_Factory',
                            'Core.Block_G.RG125_Factory', 'Core.Block_G.RG126_Factory', 'Core.Block_G.RG130_Factory',
                            'Core.Block_G.RG140_Factory', 'Core.Block_G.RG990_Factory', 'Core.Block_H.RH001_Factory',
                            'Core.Block_H.RH005_Factory', 'Core.Block_H.RH010_Factory', 'Core.Block_H.RH020_Factory',
                            'Core.Block_H.RH030_Factory', 'Core.Block_H.RH990_Factory', 'Core.Block_K.RK001_Factory',
                            'Core.Block_K.RK100_Factory', 'Core.Block_K.RK200_Factory', 'Core.Block_K.RK210_Factory',
                            'Core.Block_K.RK215_Factory', 'Core.Block_K.RK220_Factory', 'Core.Block_K.RK230_Factory',
                            'Core.Block_K.RK235_Factory', 'Core.Block_K.RK250_Factory', 'Core.Block_K.RK255_Factory',
                            'Core.Block_K.RK260_Factory', 'Core.Block_K.RK265_Factory', 'Core.Block_K.RK270_Factory',
                            'Core.Block_K.RK275_Factory', 'Core.Block_K.RK280_Factory', 'Core.Block_K.RK290_Factory',
                            'Core.Block_K.RK291_Factory', 'Core.Block_K.RK292_Factory', 'Core.Block_K.RK300_Factory',
                            'Core.Block_K.RK301_Factory', 'Core.Block_K.RK302_Factory', 'Core.Block_K.RK990_Factory'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
